---
# tasks file for apigee-opdk-start-components
- block:

  - name: Start a specific Apigee component on the node
    ignore_errors: "{{ ignore_errors | default (true) }}"
    shell: '{{ apigee_service }} {{ component_name }} start'

  - name: Wait for ready
    ignore_errors: "{{ ignore_errors | default (true) }}"
    shell: '{{ apigee_service }} {{ component_name }} wait_for_ready'
    when: validate_ready | default(true)

  when: component_name != 'all' and opdk_version | version_compare('4.16.01', '>=')

- block:

  - name: Start all Apigee components on the node
    ignore_errors: "{{ ignore_errors | default (true) }}"
    shell: '{{ apigee_all }} start'

  - name: Wait for ready
    ignore_errors: "{{ ignore_errors | default (true) }}"
    shell: '{{ apigee_all }} wait_for_ready'
    when: validate_ready | default(true)

  when: component_name is not defined or (component_name == 'all' and opdk_version | version_compare('4.16.01', '>=') )
