---
# tasks file for apigee-opdk-start-components

- name: Start Apigee
  ignore_errors: yes
  shell: '{{ apigee_all }} start'
  register: start_cmd_report
  when: opdk_version | version_compare('4.16.01', '>=')
